# Generated by Django 2.2.5 on 2019-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
