# Generated by Django 2.2.5 on 2019-09-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190914_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_choice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
