# Generated by Django 2.2.5 on 2019-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('n_fruit', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'NewPost',
                'verbose_name_plural': 'NewPosts',
            },
        ),
    ]
