# Generated by Django 2.2.5 on 2019-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='n_fruit',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], max_length=100),
        ),
    ]
