# Generated by Django 2.2.5 on 2019-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dropdown',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
